[[pages]]
path = "home.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "advice_app.py"
name = "Advice app"
icon = ":vibration_mode:"

[[pages]]
path = "contacts.py"
name = "Contact us"
icon = ":envelope_with_arrow:"