[[pages]]
path = "app/home.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "app/advice_app.py"
name = "Carousel"
icon = ":vibration_mode:"

[[pages]]
path = "app/blind_test.py"
name = "Blind Test"
icon = ":test_tube:"

[[pages]]
path = "app/lora_explainer.py"
name = "Lora Explainer"
icon = ":memo:"

[[pages]]
path = "app/prompt.py"
name = "Prompt"
icon = ":camera:"

[[pages]]
path = "app/contacts.py"
name = "Contact us"
icon = ":envelope_with_arrow:"